//go:build !ignore_autogenerated

/*
Copyright 2025 YANDEX LLC.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupConfig) DeepCopyInto(out *BackupConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupConfig.
func (in *BackupConfig) DeepCopy() *BackupConfig {
	if in == nil {
		return nil
	}
	out := new(BackupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupConfigList) DeepCopyInto(out *BackupConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BackupConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupConfigList.
func (in *BackupConfigList) DeepCopy() *BackupConfigList {
	if in == nil {
		return nil
	}
	out := new(BackupConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BackupConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupConfigSpec) DeepCopyInto(out *BackupConfigSpec) {
	*out = *in
	if in.DownloadConcurrency != nil {
		in, out := &in.DownloadConcurrency, &out.DownloadConcurrency
		*out = new(int)
		**out = **in
	}
	if in.UploadDiskRateLimit != nil {
		in, out := &in.UploadDiskRateLimit, &out.UploadDiskRateLimit
		*out = new(int)
		**out = **in
	}
	if in.UploadNetworkRateLimit != nil {
		in, out := &in.UploadNetworkRateLimit, &out.UploadNetworkRateLimit
		*out = new(int)
		**out = **in
	}
	if in.UploadConcurrency != nil {
		in, out := &in.UploadConcurrency, &out.UploadConcurrency
		*out = new(int)
		**out = **in
	}
	if in.UploadDiskConcurrency != nil {
		in, out := &in.UploadDiskConcurrency, &out.UploadDiskConcurrency
		*out = new(int)
		**out = **in
	}
	if in.TarSizeThreshold != nil {
		in, out := &in.TarSizeThreshold, &out.TarSizeThreshold
		*out = new(int64)
		**out = **in
	}
	out.Retention = in.Retention
	in.Storage.DeepCopyInto(&out.Storage)
	in.Resources.DeepCopyInto(&out.Resources)
	out.Encryption = in.Encryption
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupConfigSpec.
func (in *BackupConfigSpec) DeepCopy() *BackupConfigSpec {
	if in == nil {
		return nil
	}
	out := new(BackupConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupConfigSpecWithSecrets) DeepCopyInto(out *BackupConfigSpecWithSecrets) {
	*out = *in
	in.BackupConfigSpec.DeepCopyInto(&out.BackupConfigSpec)
	in.Storage.DeepCopyInto(&out.Storage)
	if in.Encryption != nil {
		in, out := &in.Encryption, &out.Encryption
		*out = new(BackupEncryptionConfigWithSecrets)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupConfigSpecWithSecrets.
func (in *BackupConfigSpecWithSecrets) DeepCopy() *BackupConfigSpecWithSecrets {
	if in == nil {
		return nil
	}
	out := new(BackupConfigSpecWithSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupConfigStatus) DeepCopyInto(out *BackupConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupConfigStatus.
func (in *BackupConfigStatus) DeepCopy() *BackupConfigStatus {
	if in == nil {
		return nil
	}
	out := new(BackupConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupConfigWithSecrets) DeepCopyInto(out *BackupConfigWithSecrets) {
	*out = *in
	in.BackupConfig.DeepCopyInto(&out.BackupConfig)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupConfigWithSecrets.
func (in *BackupConfigWithSecrets) DeepCopy() *BackupConfigWithSecrets {
	if in == nil {
		return nil
	}
	out := new(BackupConfigWithSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupEncryptionConfig) DeepCopyInto(out *BackupEncryptionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupEncryptionConfig.
func (in *BackupEncryptionConfig) DeepCopy() *BackupEncryptionConfig {
	if in == nil {
		return nil
	}
	out := new(BackupEncryptionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupEncryptionConfigWithSecrets) DeepCopyInto(out *BackupEncryptionConfigWithSecrets) {
	*out = *in
	out.BackupEncryptionConfig = in.BackupEncryptionConfig
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupEncryptionConfigWithSecrets.
func (in *BackupEncryptionConfigWithSecrets) DeepCopy() *BackupEncryptionConfigWithSecrets {
	if in == nil {
		return nil
	}
	out := new(BackupEncryptionConfigWithSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupRetentionConfig) DeepCopyInto(out *BackupRetentionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupRetentionConfig.
func (in *BackupRetentionConfig) DeepCopy() *BackupRetentionConfig {
	if in == nil {
		return nil
	}
	out := new(BackupRetentionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomCAReference) DeepCopyInto(out *CustomCAReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomCAReference.
func (in *CustomCAReference) DeepCopy() *CustomCAReference {
	if in == nil {
		return nil
	}
	out := new(CustomCAReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3StorageConfig) DeepCopyInto(out *S3StorageConfig) {
	*out = *in
	if in.CustomCA != nil {
		in, out := &in.CustomCA, &out.CustomCA
		*out = new(CustomCAReference)
		**out = **in
	}
	if in.AccessKeyIDRef != nil {
		in, out := &in.AccessKeyIDRef, &out.AccessKeyIDRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.AccessKeySecretRef != nil {
		in, out := &in.AccessKeySecretRef, &out.AccessKeySecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3StorageConfig.
func (in *S3StorageConfig) DeepCopy() *S3StorageConfig {
	if in == nil {
		return nil
	}
	out := new(S3StorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3StorageConfigWithSecrets) DeepCopyInto(out *S3StorageConfigWithSecrets) {
	*out = *in
	in.S3StorageConfig.DeepCopyInto(&out.S3StorageConfig)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3StorageConfigWithSecrets.
func (in *S3StorageConfigWithSecrets) DeepCopy() *S3StorageConfigWithSecrets {
	if in == nil {
		return nil
	}
	out := new(S3StorageConfigWithSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3StorageConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfigWithSecrets) DeepCopyInto(out *StorageConfigWithSecrets) {
	*out = *in
	in.StorageConfig.DeepCopyInto(&out.StorageConfig)
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(S3StorageConfigWithSecrets)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfigWithSecrets.
func (in *StorageConfigWithSecrets) DeepCopy() *StorageConfigWithSecrets {
	if in == nil {
		return nil
	}
	out := new(StorageConfigWithSecrets)
	in.DeepCopyInto(out)
	return out
}
