apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cnpg-plugin-wal-g.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cnpg-plugin-wal-g.labels" . | nindent 4 }}
